### ISSUE TITLE
Which Common Voice version?

### ISSUE THREAD

**Issue by patrickvonplaten** [facebookresearch/CPC_audio#22]
Thanks for open-sourcing the code to reproduce the results of the paper. 

Which Common Voice Version was used to produce the evaluation/test results? Was it Common Voice 1,2,3 or 4?

**Comment by patrickvonplaten** [comment]
Common Voice 3 worked for me - it included all the necessary ids.

**Comment by KarenMars** [comment]
> Common Voice 3 worked for me - it included all the necessary ids.

Hi, I also use Common Voice 3, however, I met this problem when I convert the sampling rate for the Spanish dataset with the split provided in this repo:

Command: 
```
PATH_DB=/corpora/CommonVoice/clips
# Path to the phone set 
PATH_PDB=/corpora/CommonVoiceSplit/common_voices_splits/es/phones_test.txt
# Output path
PATH_OUT=/corpora/CommonVoice/clips_16k
# convert 
echo "Converting ......"
python utils/adjust_sample_rate.py $PATH_DB $PATH_PDB $PATH_OUT
echo "Done ......"
```

Logs:
```
formats: can't open input file `/corpora/CommonVoice/clips/common_voice_es_18406510.mp3': 
Traceback (most recent call last):
  File "utils/adjust_sample_rate.py", line 98, in <module>
    main(sys.argv[1:])
  File "utils/adjust_sample_rate.py", line 93, in main
    adjust_sample_rate(args.path_db, out_list,
  File "utils/adjust_sample_rate.py", line 24, in adjust_sample_rate
    data, sr = torchaudio.load(path_in)
  File "/software/conda_install/envs/zs_cpc/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 104, in load
    signal = torch.ops.torchaudio.sox_io_load_audio_file(
RuntimeError: Error loading audio file: failed to open file.
100% (8727 of 8727) |#####################| Elapsed Time: 0:02:24 Time:  0:02:24
Done ......
```

I also manually loaded the file `common_voice_es_18406510.mp3` with `torchaudio.load(path_in)`, it had the same error.

Have you also encountered the same problem? Thank you very much.
